### ISSUE TITLE
Map panning and zooming not working on some Android devices

### ISSUE THREAD

**Issue by rajeshlv** [LukeMizuhashi/apple-mapkit-js#3]
In some android devices(eg: one plus 6) the map panning and zooming functionality is not working. But in some other Android devices it is working fine.

**Comment by LukeMizuhashi** [comment]
This is just a copy-paste job of Apple's Mapkit. Please checkout their docs and forums for support on zooming and panning.

**Comment by derWebdesigner** [comment]
Hint for others: It's simply an issue with a touch event that was changed within Chrome. The latest versions of Mapkit did update this behaviour and fix the issue.
